# Install packages
 install.packages("data.table")
 install.packages("plyr")
 install.packages("MASS")
 install.packages("fields")
 install.packages("readxl")
 install.packages("gridExtra")
 install.packages("cli")
 install.packages("imager")
 #install.packages("readr")